app = "ocr-extractor-app"
primary_region = "lax"

[build]
  image = "abdullak123/ml-api:latest"

[env]
  PORT = "8000"
  HOST = "0.0.0.0"
  PYTHONUNBUFFERED = "1"
  WORKERS = "4"
  TIMEOUT = "300"
  MAX_REQUESTS = "1000"
  KEEP_ALIVE = "75"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

[[vm]]
  cpu_kind = "shared"
  cpus = 4
  memory_mb = 4096
